<?php
/**
 * Onepage Checkout Success Payment Information Block
 *
 * @link  https://docs.unzer.com/
 */

/**
 * @var $block \Unzer\PAPI\Block\Checkout\Success\AdditionalPaymentInformation
 */

/** @var string $additionalInformation */
$additionalInformation = $block->getAdditionalPaymentInformation();
if (!empty($additionalInformation)):
    ?>
    <div class="unzer-additional-payment-information">
        <h3 class="unzer-additional-payment-information-title">
            <?php echo __('Payment information'); ?>
        </h3>

        <p>
            <?php echo $additionalInformation ?>
        </p>
    </div>

    <script>
        require([
            'Magento_Customer/js/customer-data'
        ], function (customerData) {
            customerData.invalidate(['cart']);
        })
    </script>
<?php endif; ?>
