<?php
/**
 * Onepage Checkout Success Payment Information Block
 *
 * Copyright (C) 2021 Unzer GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @link  https://docs.unzer.com/
 *
 * @author Justin Nuß
 *
 * @package  unzerdev/magento2
 */

/**
 * @var $block \Unzer\PAPI\Block\Checkout\Success\AdditionalPaymentInformation
 */

/** @var string $additionalInformation */
$additionalInformation = $block->getAdditionalPaymentInformation();
if (!empty($additionalInformation)):
    ?>
    <div class="unzer-additional-payment-information">
        <h3 class="unzer-additional-payment-information-title">
            <?php echo __('Payment information'); ?>
        </h3>

        <p>
            <?php echo $additionalInformation ?>
        </p>
    </div>

    <script>
        require([
            'Magento_Customer/js/customer-data'
        ], function (customerData) {
            customerData.invalidate(['cart']);
        })
    </script>
<?php endif; ?>
