<?php
/**
 * Onepage Checkout Success Payment Information Block
 *
 * @link  https://docs.unzer.com/
 */

/**
 * @var $block \Unzer\PAPI\Block\Checkout\Success\AdditionalPaymentInformation
 */

/** @var string|null $unzerPaymentId */
$unzerPaymentId = $block->getUnzerPaymentId();
if ($unzerPaymentId !== null):
    ?>
    <p id="UnzerPaymentId">
        <?php echo $block->escapeHtml(__('Your Unzer payment # is:')) ?>
        <span data-testid="Unzer-Payment-Id"><?php echo $block->escapeHtml($unzerPaymentId) ?></span>.
    </p>
<?php endif; ?>
<?php
/** @var string $additionalInformation */
$additionalInformation = $block->getAdditionalPaymentInformation();
if (!empty($additionalInformation)):
    ?>
    <div class="unzer-additional-payment-information">
        <h3 class="unzer-additional-payment-information-title">
            <?php echo __('Payment information'); ?>
        </h3>

        <p>
            <?php echo $additionalInformation ?>
        </p>
    </div>

    <script>
        require([
            'Magento_Customer/js/customer-data'
        ], function (customerData) {
            customerData.invalidate(['cart']);
        })
    </script>
<?php endif; ?>
