<?php
/**
 * Onepage Checkout Success Plugin Block
 *
 * @link  https://docs.unzer.com/
 */

/**
 * @var $block \Magento\Checkout\Block\Success
 */
?>

<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
    <?php endif;?>

    <p>
        <?php echo __('The current state of your payment could not be determined, ' .
            'we will inform you when the result is present and your order was successful.'); ?>
    </p>

    <p>
        <?php echo __('There will be no notification if the payment has been aborted.'); ?>
        <?php echo __('Please contact us for further information.') ?>
    </p>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue"
               href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>">
                <span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span>
            </a>
        </div>
    </div>
</div>
