<?php
declare(strict_types=1);

/**
 * Customer Account Order Invoice Information Block
 *
 * @link  https://docs.unzer.com/
 */

/**
 * @var $block \Unzer\PAPI\Block\Info\PaylaterInvoiceB2b
 */
?>
<dl class="payment-method invoice">
    <dt class="title"><?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <?php $additionalInformation = $block->getMethod()->getAdditionalPaymentInformation($this->getOrder()); ?>
    <?php if (!empty($additionalInformation)): ?>
    <dd class="content">
        <strong><?php echo $block->escapeHtml(__('Payment information')) ?></strong><br />
        <?php echo $additionalInformation ?>
    </dd>
    <?php endif; ?>
</dl>
