<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Vault\Api\Data\PaymentTokenInterface;
use Magento\Vault\Block\CardRendererInterface;

/** @var CardRendererInterface|Template $block */

$ccNumberView = $block->escapeHtml($block->getNumberLast4Digits());
?>
<tr class="vault-card-row">
    <td class="col card-number" data-th="<?= $block->escapeHtml(__('Card Number')) ?>">
        <?= /* @noEscape */
        $ccNumberView ?>
    </td>

    <td class="col card-expire" data-th="<?= $block->escapeHtml(__('Expiration Date')) ?>">
        <?= $block->escapeHtml($block->getExpDate()) ?>
    </td>

    <td class="col card-type" data-th="<?= $block->escapeHtml(__('Type')) ?>">
        <?= $block->escapeHtml($block->getBrand()) ?>
    </td>

    <td class="col actions" data-th="<?= $block->escapeHtml(__('Actions')) ?>">
        <form class="form"
              action="<?= $block->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
              method="post">
            <?= $block->getBlockHtml('formkey') ?>

            <input type="hidden"
                   name="<?= PaymentTokenInterface::PUBLIC_HASH ?>"
                   value="<?= $block->getToken()->getPublicHash() ?>"/>

            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                        "Magento_Vault/js/customer_account/deleteWidget": {
                            "type": "popup",
                            "modalClass": "my-credit-cards-popup",
                            "toggleEvent": "click",
                            "title": "<?= $block->escapeHtml(__('Delete')) ?>",
                            "content": "<?= $block->escapeHtml(__('Are you sure you want to delete this card: %1?',
                        $ccNumberView)) ?>"
                        }
                    }'>
                <span><?= $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
