<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Unzer\PAPI\Block\Customer\DirectDebitRenderer;
use Magento\Vault\Api\Data\PaymentTokenInterface;

/** @var Template|DirectDebitRenderer $block */
$maskedIban = (string)$block->escapeHtml($block->getMaskedIban());
$holder = (string)$block->escapeHtml($block->getAccountHolder());
?>

<tr class="sepa-row">
    <td class="col sepa-iban" data-th="<?= $block->escapeHtmlAttr(__('IBAN')) ?>">
        <?= /* @noEscape */
        $maskedIban ?>
    </td>
    <td class="col sepa-holder" data-th="<?= $block->escapeHtmlAttr(__('Account Holder')) ?>">
        <?= /* @noEscape */
        $holder ?>
    </td>
    <td class="col sepa-type" data-th="<?= $block->escapeHtmlAttr(__('Type')) ?>">
        <?= $block->escapeHtml(__('SEPA Direct Debit')) ?>
    </td>
    <td class="col actions" aria-label="<?= $block->escapeHtmlAttr(__('Actions')) ?>">
        <form class="form"
              action="<?= $block->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
              method="post">
            <?= $block->getBlockHtml('formkey') ?>
            <input
                    name="<?= /* @noEscape */
                    PaymentTokenInterface::PUBLIC_HASH ?>"
                    value="<?= /* @noEscape */
                    $block->getToken()->getPublicHash() ?>"
                    type="hidden"/>
            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                        "Magento_Vault/js/customer_account/deleteWidget": {
                            "type": "popup",
                            "modalClass": "my-credit-cards-popup",
                            "toggleEvent": "click",
                            "title": "<?= $block->escapeHtmlAttr(__('Delete')) ?>",
                            "content": "<?= $block->escapeHtmlAttr(__('Are you sure you want to delete this SEPA mandate: %1 (%2)?',
                        $maskedIban, $holder)) ?>"
                        }
                    }'>
                <span><?= $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
