<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Magento\Vault\Api\Data\PaymentTokenInterface;
use Unzer\PAPI\Block\Customer\PaypalRenderer;

/** @var Template|PaypalRenderer $block */
$payerEmail = (string)$block->escapeHtml($block->getPayerEmail());
?>

<tr class="vault-paypal-row">
    <td class="col card-number" data-th="<?= $block->escapeHtml(__('Account')) ?>">
        <?= $payerEmail ?>
    </td>

    <td class="col card-expire" data-th="<?= $block->escapeHtml(__('Expiration Date')) ?>">
        &nbsp;
    </td>

    <td class="col card-type" data-th="<?= $block->escapeHtml(__('Type')) ?>">
        <?= $block->escapeHtml(__('PayPal')) ?>
    </td>

    <td class="col actions" data-th="<?= $block->escapeHtml(__('Actions')) ?>">
        <form class="form"
              action="<?= $block->escapeUrl($block->getUrl('vault/cards/deleteaction')) ?>"
              method="post">
            <?= $block->getBlockHtml('formkey') ?>

            <input type="hidden"
                   name="<?= PaymentTokenInterface::PUBLIC_HASH ?>"
                   value="<?= $block->getToken()->getPublicHash() ?>"/>

            <button type="submit"
                    class="action delete"
                    data-mage-init='{
                        "Magento_Vault/js/customer_account/deleteWidget": {
                            "type": "popup",
                            "modalClass": "my-credit-cards-popup",
                            "toggleEvent": "click",
                            "title": "<?= $block->escapeHtmlAttr(__('Delete')) ?>",
                            "content": "<?= $block->escapeHtmlAttr(
                        __('Are you sure you want to delete this PayPal account: %1?', $payerEmail)
                    ) ?>"
                        }
                    }'>
                <span><?= $block->escapeHtml(__('Delete')) ?></span>
            </button>
        </form>
    </td>
</tr>
