<?php
/**
 * Order Invoice Information Block
 *
 * Copyright (C) 2021 Unzer GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @link  https://docs.unzer.com/
 *
 * @author Justin Nuß
 *
 * @package  unzerdev/magento2
 */

/**
 * @var $block \Unzer\PAPI\Block\Info\InvoiceSecured
 */
?>
<div class="order-payment-method-name">
    <?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?>
</div>
<table class="data-table admin__table-secondary">
    <tr>
        <th colspan="2" style="text-align: center; font-weight: bold;">
            <?php echo $block->escapeHtml(__('Unzer Payment Information')); ?>
        </th>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('Account Holder')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getAccountHolder()); ?></td>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('IBAN')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getAccountIban()); ?></td>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('BIC')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getAccountBic()); ?></td>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('Reference')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getReference()); ?></td>
    </tr>
    <tr>
        <th colspan="2" style="text-align: center; font-weight: bold;">
            <?php echo $block->escapeHtml(__('Customer Information')); ?>
        </th>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('Salutation')); ?>:</th>
        <td><?php echo $block->escapeHtml(__($block->getCustomerSalutation())); ?></td>
    </tr>
    <?php if ($block->getCustomerBirthdate()): ?>
        <tr>
            <th><?php echo $block->escapeHtml(__('Birthdate')); ?>:</th>
            <td><?php echo $block->escapeHtml($block->getCustomerBirthdate()); ?></td>
        </tr>
    <?php endif; ?>
</table>