<?php
/**
 * @var $block \Heidelpay\Gateway2\Block\Info\Invoice
 */
?>
<div class="order-payment-method-name">
    <?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?>
</div>
<table class="data-table admin__table-secondary">
    <tr>
        <th colspan="2" style="text-align: center; font-weight: bold;">
            <?php echo $block->escapeHtml(__('Heidelpay Payment Information')); ?>
        </th>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('Account Holder')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getAccountHolder()); ?></td>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('IBAN')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getAccountIban()); ?></td>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('BIC')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getAccountBic()); ?></td>
    </tr>
    <tr>
        <th><?php echo $block->escapeHtml(__('Identification Number')); ?>:</th>
        <td><?php echo $block->escapeHtml($block->getIdentificationNumber()); ?></td>
    </tr>
</table>