<?php
/**
 * Order Invoice PDF Information Block
 *
 * Copyright (C) 2019 heidelpay GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @link  https://docs.heidelpay.com/
 *
 * @author Justin Nuß
 *
 * @package  heidelpay/magento2-merchant-gateway
 */

/**
 * @var $block \Heidelpay\MGW\Block\Info\InvoiceGuaranteed
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?>
{{pdf_row_separator}}
<?php echo $block->escapeHtml(__('Account Holder')); ?>
<?php echo ': '; ?>
<?php echo $block->escapeHtml($block->getAccountHolder()) ?>
{{pdf_row_separator}}
<?php echo $block->escapeHtml(__('IBAN')); ?>
<?php echo ': '; ?>
<?php echo $block->escapeHtml($block->getAccountIban()) ?>
{{pdf_row_separator}}
<?php echo $block->escapeHtml(__('BIC')); ?>
<?php echo ': '; ?>
<?php echo $block->escapeHtml($block->getAccountBic()) ?>
{{pdf_row_separator}}
<?php echo $block->escapeHtml(__('Identification Number')); ?>
<?php echo ': '; ?>
<?php echo $block->escapeHtml($block->getIdentificationNumber()) ?>