<?php
/**
 * Order Invoice PDF Information Block
 *
 * Copyright (C) 2021 - today Unzer GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * @link  https://docs.unzer.com/
 *
 * @author Justin Nuß
 *
 * @package  unzerdev/magento2
 */

/**
 * @var $block \Unzer\PAPI\Block\Info\Invoice
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?>

<?php if($block->hasAccountData()): ?>
    {{pdf_row_separator}}
    <?php echo $block->escapeHtml(__('Account Holder')); ?>
    <?php echo ': '; ?>
    <?php echo $block->escapeHtml($block->getAccountHolder()) ?>
    {{pdf_row_separator}}
    <?php echo $block->escapeHtml(__('IBAN')); ?>
    <?php echo ': '; ?>
    <?php echo $block->escapeHtml($block->getAccountIban()) ?>
    {{pdf_row_separator}}
    <?php echo $block->escapeHtml(__('BIC')); ?>
    <?php echo ': '; ?>
    <?php echo $block->escapeHtml($block->getAccountBic()) ?>
    {{pdf_row_separator}}
    <?php echo $block->escapeHtml(__('Reference')); ?>
    <?php echo ': '; ?>
    <?php echo $block->escapeHtml($block->getReference()) ?>
<?php endif; ?>
