<?php
/**
 * Order Invoice PDF Information Block
 *
 * @link  https://docs.unzer.com/
 */

/**
 * @var $block \Unzer\PAPI\Block\Info\PaylaterInvoice
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?>

<?php if($block->hasAccountData()): ?>
    {{pdf_row_separator}}
    <?php echo $block->escapeHtml(__('Account Holder')); ?>
    <?php echo ': '; ?>
    <?php echo $block->escapeHtml($block->getAccountHolder()) ?>
    {{pdf_row_separator}}
    <?php echo $block->escapeHtml(__('IBAN')); ?>
    <?php echo ': '; ?>
    <?php echo $block->escapeHtml($block->getAccountIban()) ?>
    {{pdf_row_separator}}
    <?php echo $block->escapeHtml(__('BIC')); ?>
    <?php echo ': '; ?>
    <?php echo $block->escapeHtml($block->getAccountBic()) ?>
    {{pdf_row_separator}}
    <?php echo $block->escapeHtml(__('Reference')); ?>
    <?php echo ': '; ?>
    <?php echo $block->escapeHtml($block->getReference()) ?>
<?php endif; ?>
